name: Continuous Deployment
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish:
    name: Publishing crate
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@master
      - name: Installing Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Publishing to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CRATES_IO_TOKEN }} --allow-dirty
